runtime: python39

env_variables:
  # Database Configuration (update after creating Cloud SQL)
  DATABASE_URL: "postgresql://prabhuser:YourSecurePassword123@/prabhdb?host=/cloudsql/myprabh:us-central1:my-prabh-db"
  
  # OpenRouter AI API
  OPENROUTER_API_KEY: "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"
  
  # Application Settings
  FLASK_ENV: "production"
  SECRET_KEY: "myprabh-production-secret-key-2024-secure"
  
  # Email Configuration
  ADMIN_EMAIL: "abhay@aiprabh.com"
  
  # Google Cloud Settings
  GOOGLE_CLOUD_PROJECT: "myprabh"
  
  # Performance Settings
  MEMORY_LIMIT_MB: "2048"
  CPU_LIMIT: "1"

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Health checks
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Static file handling
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always